### PR TITLE
`zap` and `unzap` are now a single binary: `zap`

### PR DESCRIPTION
**Pull request by ureeves**
Both archiving and extraction are available from a single binary, each triggered by their own subcommand.

### CODE REVIEW

**Comment by Speykious** [comment]
I was the one who specifically asked for both binaries to be separate. The reason is that I like how Zip comes with both `zip` and `unzip` commands. It makes the commands shorter and a bit easier to read imho.

**Comment by ureeves** [comment]
Both are okay choices and in the end it comes down to personal preference. This is the `zip`/`unzip` way, as opposed to the `tar` way.
Feel free to close the PR if you don't want to take it.

**Comment by Speykious** [comment]
Guess I'll wait on @SteveGremory to think about this

**Comment by SteveGremory** [comment]
I mean, initially I wanted one binary myself so...

**Review by SteveGremory — APPROVED** [review]

**Pull request merged**
